# Generated by Django 6.0.4 on 2026-04-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hourlywaterconsumption_waterevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterevent',
            name='event_type',
            field=models.CharField(choices=[('pump_on', 'Pump ON'), ('leak', 'Leak'), ('empty', 'Empty')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='waterevent',
            unique_together={('event_type', 'start_time')},
        ),
    ]
