# Generated by Django 6.0.4 on 2026-06-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_waterevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waterlevel',
            name='battery_percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waterlevel',
            name='battery_voltage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
