# Generated by Django 6.0.4 on 2026-07-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('report_interval', models.IntegerField(choices=[(1, 'Every 1 Minutes'), (15, 'Every 15 Minutes'), (30, 'Every 30 Minutes'), (60, 'Every Hour'), (120, 'Every 2 Hours'), (360, 'Every 6 Hours'), (720, 'Every 12 Hours'), (1440, 'Daily')], default=60)),
                ('include_water_level', models.BooleanField(default=True)),
                ('include_daily_usage', models.BooleanField(default=True)),
                ('include_battery', models.BooleanField(default=True)),
                ('include_voltage', models.BooleanField(default=True)),
                ('include_wifi', models.BooleanField(default=False)),
                ('tank_full_notification', models.BooleanField(default=True)),
                ('tank_empty_notification', models.BooleanField(default=True)),
                ('battery_low_notification', models.BooleanField(default=True)),
                ('battery_low_percentage', models.IntegerField(default=40)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
